settings:
  anchor: true
  inject: true
  indent: 3
formatter: "markdown table"
sort:
  enabled: true
  by: required
content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
recursive:
  enabled: true
  path: modules